[package]
name = "kioto"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5.3"
clap = "4.5.4"
crossterm = "0.27.0"
dirs = "5.0.1"
polodb_core = "4.4.1"
ratatui = "0.26.1"
rpassword = "7.3.1"
serde = "1.0.114"
strum = "0.26.2"
tokio = "1.36.0"
uuid = "1.3.0"
